{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-service-monitor
spec:
  endpoints:
    - path: /metrics
      port: http
      scheme: http
  selector:
    {{- include "eck-custom-resources-operator.labels" . | nindent 4 }}
{{- end }}
