# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/es.eck.github.com_indices.yaml
- bases/es.eck.github.com_indextemplates.yaml
- bases/es.eck.github.com_indexlifecyclepolicies.yaml
- bases/es.eck.github.com_snapshotlifecyclepolicies.yaml
- bases/es.eck.github.com_roles.yaml
- bases/es.eck.github.com_users.yaml
- bases/es.eck.github.com_ingestpipelines.yaml
- bases/es.eck.github.com_snapshotrepositories.yaml
- bases/kibana.eck.github.com_savedsearches.yaml
- bases/kibana.eck.github.com_indexpatterns.yaml
- bases/kibana.eck.github.com_visualizations.yaml
- bases/kibana.eck.github.com_dashboards.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_indices.yaml
#- patches/webhook_in_indextemplates.yaml
#- patches/webhook_in_indexlifecyclepolicies.yaml
#- patches/webhook_in_snapshotlifecyclepolicies.yaml
#- patches/webhook_in_roles.yaml
#- patches/webhook_in_users.yaml
#- patches/webhook_in_ingestpipelines.yaml
#- patches/webhook_in_snapshotrepositories.yaml
#- patches/webhook_in_savedsearches.yaml
#- patches/webhook_in_indexpatterns.yaml
#- patches/webhook_in_visualizations.yaml
#- patches/webhook_in_dashboards.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_indices.yaml
#- patches/cainjection_in_indextemplates.yaml
#- patches/cainjection_in_indexlifecyclepolicies.yaml
#- patches/cainjection_in_snapshotlifecyclepolicies.yaml
#- patches/cainjection_in_roles.yaml
#- patches/cainjection_in_users.yaml
#- patches/cainjection_in_ingestpipelines.yaml
#- patches/cainjection_in_snapshotrepositories.yaml
#- patches/cainjection_in_savedsearches.yaml
#- patches/cainjection_in_indexpatterns.yaml
#- patches/cainjection_in_visualizations.yaml
#- patches/cainjection_in_dashboards.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
